### ISSUE TITLE
GetTopTenUsers return value doesn't match schema in web docs

### ISSUE THREAD

**Issue by LaunchBox-C-Beats** [RetroAchievements/api-docs#1]
The [web doc](https://api-docs.retroachievements.org/v1/feed/get-top-ten-users.html) states the return for this end point should be an array of class objects who's property names are: userName, totalPoints, and totalRatioPoints. Instead the property names return as 1,2,3. Right now the return I get from the API looks like the following:

```
[{"1":"MaxMilyin","2":407445,"3":1623980},{"1":"HippopotamusRex","2":356675,"3":2235447},{"1":"Sarconius","2":336120,"3":1626901},{"1":"Infernum","2":278175,"3":977109},{"1":"Andrey199650","2":271088,"3":731229},{"1":"guineu","2":270074,"3":781577},{"1":"Wendigo","2":244793,"3":1405584},{"1":"ChronoGear","2":241798,"3":1116042},{"1":"ShadwSonic","2":228731,"3":811783},{"1":"AmericanNinja","2":226510,"3":715895}]
```

**Comment by wescopeland** [comment]
Transferred to api-docs.
