### ISSUE TITLE
switch to pnpm

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/api-docs#45]
Will need to also update the build server.

**Comment by falsepopsky** [comment]
I can help like i did in the js repo, the previous site was hosted on vercel, if it's still there you can enable corepack.

**Comment by wescopeland** [comment]
@falsepopsky Thanks for helping! I'll probably have to tackle the one in api-docs. The site isn't hosted on Vercel anymore, so I'll need to install pnpm on the build server.
