### ISSUE TITLE
Ranked user list

### ISSUE THREAD

**Issue by taras240** [RetroAchievements/api-docs#49]
It would be a good idea to add an endpoint that returns a ranked list with an offset of ±N users relative to the target, as well as the top 10 users. This way, the nearest competitors would be visible.

**Comment by wescopeland** [comment]
Hi!

Thanks for making an enhancement request. Unfortunately, it's going to get lost if it's an issue in the docs repo. Please repost this request in our dedicated discussion thread: https://github.com/RetroAchievements/RAWeb/discussions/2081

Thanks!
